language: node_js
node_js:
- '10'
services:
- mongodb
before_script:
- npm start &
- sleep 5
deploy:
  provider: heroku
  app: ad-steve-maibach-chat
  api_key:
    secure: mFaZss90T7sUF7BltO7LO1eCAQZXaLIQFUehiHMfadD9q27ztJvNmO0KpOao39R+Ir0X7pv8V1aFCX/FnFJqurZSdsdO67Of/UE+u++jV3yIyfWrnrbMQMX5eaFIOkJZLeWlBaCSqgu9MEejq+kN+EAubC4kkltKM7EoxLSi48l30Hg2m2AdcKbTjnSDSs+5XFtPRmmfBeZNVDtwLBk4ISRP3MlbZ18cZCPLxkz/iwU+Jf8NMNYiPkFVfEi1w89o40TnjEbrNY3Givdhs8BjTr4ZuhNOtV5DEpV7a4zOO914UfnK10Tw7x8aJKYN5/glbyjgXk+P4c9gbTFDzEMtMpcvuV5qm0/KpAbxEbAWqMp4IMgun2LYMlqc+wTcsxwSsJV6nh3cIZlGnOI1xNG7DQGurnGF1BlNPJoLBwhAk863WB+JgjRI9mxZGyXBolN3rZOli0GpMBUQztFl+csBwHcTK0Mhv6z+tNLFPhCWLNl93nA28JzHcy5zZ82vtiDlutIaKaeZp4419z6IgDu42KekOLURlB3FRpI1ApeOonUhXVJOhUIDCkGPLKYKJ8gRFdesMrJ1VVMnCMudEHNzDWxs8oy8doU/B3swc+8XYksuU3/Z/AnOZftYLH9MbiOaslqYPUTcYR//bGWxH9icRnxFQvlZZeW4NgZr2P1hB9g=
