language: node_js
node_js:
- '10'
services:
- mongodb
before_script:
- npm start &
- sleep 5
deploy:
  provider: heroku
  app: ad-steve-maibach-chat
  api_key:
    secure: kFvLhKU4IVRnMrWKbY3BWBUqjJqPSzfub+zJXGLKHxA+EV4tkO/C5/U+DEqWNrSEcVayUOPAcQIsjQpubjbXNP/4jX4DQTQDJgo9vzMGvFeALVjEmdBitNzGYGgUtKyYviNLpEepouJacJq4U0SU+QaQwKqaymu+yvSbO6rxUouDITWtbPSGywqVlgSCN/x2MesdaY/om0mJPwpuDKdXPVnTCeZuLghxaweo+dLooYHbGK/GYTfOcCYklXICKKR/G7WeQPvUNuF8TACSlklrk0MoeoVL17GDcgHhTyT62mFGueF0I2wPD+zT07dTDjKT0SrxfpFsRce/qQawRU46Mh3G1lQGfQ1EtMhwgrYAhcIY9IgcOQbYatzwZn8hj9d0Js6dtyzJxdyq2qkLxqOhu4N5g/BJE/YcmL5NqXPNp/DRjyiO279dxYqAJvXJYViSOFW3PNBi5wWOCZzkGVk9Lv0hwjBj/g6pyoKCS2dAd0ECkds9CaQnAE+TMHv2nkQDL5gvqR7+Gx4VG8mCkuiZDhIvU94ixkFqLimybVPxy2EyM8jw5Lzs4LRGzJFrBGNXqQlydev/R9cy2rreDfXgB4gXaAxOdTrUVT4TVvKaljo9Rs0U1TxPgMRD/h4OOXv4sEkC19vEpJW2o87BQoJytD2NPQyzg8gxn84AYNe+S6I=
