language: node_js
node_js:
- '10'
services:
- mongodb
before_script:
- npm start &
- sleep 5
deploy:
  provider: heroku
  app: ad-steve-maibach-chat
  api_key:
    secure: FxVOP27R2frXtPKJO1hekcS+DHpYBKj7VRgubLTbkOlQctdHKIDxXdgIcWZVuU2h6iBRUFzy/VDi17gJGGsC6WitKZazt6my56QJJU+Emoc5KiYe8wo/Rl4xeVl/tUDn0qNVLMxErfTCsa/K0TdnmUApEt++fjMM0PnjQfjpSe07ZXqHwX0pWrXznaFrLKml2cMxjGSwP4JOn6n6J+jX9/RbrQRQ0SBoISVIxI4t6a4tHyagQ2iaz+4ldQasTEg6yYrLwzHp0YLmkTcVr+vjCG8WK0CM5jN+Ll28WaNuEl1c/kDTaKxaiGbFtBLnAeUL11IMs48YmNrbTsSiaRiBgFchPgCKMJqnoyjkMQjqdWXe1vXkyaUZONDH8MyDskO1LkTN6SAbsqQhRt9s1pou2HCx93u1MFkgrpeokbl0l2r0SBpeYK/b0/1cYMksPfLy55uxIK2g0y6Th4wmwjzDwHcqect8+IctQgAkLm1jD+XtO3K3ExGfa6CJhJMieTgVa4dPx/Eab1/+erZgKJ+DehW9sdeFlP92ACflSBbyVImq7qlB4HrW5kQgHMM3EAr6xu8AeLLTrC8kLetP3bby5IHS5iaQAb6UQW7YQN7N48Z98ej7hOh1AZLLGMjQhlUUrFcZnNesvawVk5jV+loDAQWbyJsLyipamH3JHDd0ZSQ=
